language: node_js
node_js: 10
branches:
  only:
  - master
  - /^greenkeeper/.*$/
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
addons:
  chrome: stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn lint
- yarn test
- yarn build
